###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [ ]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [ ]:
get_state(4)

[[12  3  9 14]
 [13 15  0  7]
 [ 4  8  1 10]
 [11  5  6  2]]


[12, 3, 9, 14, 13, 15, 0, 7, 4, 8, 1, 10, 11, 5, 6, 2]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [ ]:
def count_inversion(arr):
    arr = [i for i in arr if i !=0]
    print(arr)
    inversion = []
    for i in range(len(arr)):    
        count = 0
        for j in range(i+1,len(arr)):        
            if arr[i] > arr[j]: 
                count = count + 1
        inversion.append(count)
    print(inversion)
    return sum(inversion)

In [ ]:
s = get_state(3)
count_inversion(s)

In [ ]:
s.index(0)

2

# Solvability Rules

In [ ]:
N = 4

In [ ]:
S = get_state(N)

[[ 8 13  1  0]
 [15  5 10  7]
 [ 3  2 12  6]
 [11  9 14  4]]


In [ ]:
R = int(np.ceil(N - S.index(0)/N))
R

4

In [ ]:
I = count_inversion(S)
I

[8, 13, 1, 15, 5, 10, 7, 3, 2, 12, 6, 11, 9, 14, 4]
[7, 11, 0, 11, 3, 6, 4, 1, 0, 4, 1, 2, 1, 1, 0]


52

In [ ]:
# find row position of the blank tile
R = get_row_for_blank(S) # define the method before this cell

In [ ]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not

def isSolvable(initialState):
  N = ?
  I = ?
  R = ?
  # decide solvability


SyntaxError: ignored

In [ ]:
S = get_state(N)
isSolvable(S)
