<a href="https://colab.research.google.com/github/aftabrakinsad/AI/blob/master/Week_07_N_Puzzle_Solvability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###### To solve a puzzle, you are given an initial state and a goal state.
###### Target is to reach goal state from initial state using puzzle rules.
######  We can move blank tile only on left, right, up, and down
![Capture.JPG](attachment:Capture.JPG)

# Generate an intial state of NPuzzle

In [ ]:
import numpy as np
import random
def get_state(N):    
    state = [item for item in range(N*N)]# [0,1,2,...,15]
    #print(state)
    random.shuffle(state)
    #print(state)
    tmp = np.array(state)
    print(tmp.reshape(N,N))
    return state

In [ ]:
get_state(3)

[[8 1 7]
 [0 5 2]
 [6 3 4]]


[8, 1, 7, 0, 5, 2, 6, 3, 4]

# Calculate inversion

Inversion is a pair of tiles that are in the reverse order from where they ought to be. In our case, the bigger number is in front of the smaller one.



![Capture.JPG](attachment:Capture.JPG)

In [ ]:
def count_inversion(state):
    #arr = [i for i in arr if i !=0]
    print(state)
    inversion = []
    for i in range(len(state)):    
        count = 0
        for j in range(i+1,len(state)):        
            if state[i] > state[j]: 
                count = count + 1
        inversion.append(count)
    #print(inversion)
    return sum(inversion)

In [ ]:
s = get_state(4)
count_inversion(s)

[[13  3  5 11]
 [ 0 10  1  6]
 [ 2 12  9 14]
 [15  4  7  8]]
[13, 3, 5, 11, 0, 10, 1, 6, 2, 12, 9, 14, 15, 4, 7, 8]


51

# Solvability Rules

In [13]:
# apply the rules to decide solvability
#  N, I, R
# define a method to return solvability (input S)
# return True if solvable or False if not
import math
def isSolvable(initialState):
    n = math.sqrt(len(initialState))
    i = count_inversion(initialState)
    r = int(np.ceil(N - initialState.index(0)/N))
    print(n)
    print(r)
    print(i)
    # decide solvability
    if n%2 != 0 and i%2 == 0:
        print("true - 1")

    elif n%2==0 and r%2!=0 and i%2 == 0:
        print("true - 2")

    elif n%2==0 and r%2==0 and i%2 != 0:
        print("true - 3")
        
    else:
        print("false")

In [14]:
N =3
initialState = get_state(N)
isSolvable(initialState)

[[6 7 0]
 [4 3 8]
 [5 1 2]]
[6, 7, 0, 4, 3, 8, 5, 1, 2]
3.0
3
22
true - 1
